/*
Here, business insights are generated from facts and dimension tables created in
the gold schema. All questions are answered based on information from dim_ and fct_.
 

*/
use gold
-- ++++++++++++++++++++++++++++++++++++++++++++++
-- Q1. How many total visits occurred each month?
-- ++++++++++++++++++++++++++++++++++++++++++++++
-- every visit is recorded as per visit_id. 
select * from gold.fct_visits

select
	visit_date,
    count(visit_id) as total_visits
from
	fct_visits
group by visit_date
order by visit_date
-- this query only delivers visits per day. we need to extract/view the month of visit_date

select
	DATE_FORMAT(visit_date, '%M %Y') AS visit_month_year,  
    count(visit_id) as number_visits
from
	fct_visits
group by visit_month_year 								-- group by month
order by number_visits 
-- Formatting the data according to month and year reflects vists by month of the years.
-- The questions seeks to find the visit by month only. we eliminate the year (%Y) of the month

select
	DATE_FORMAT(visit_date, '%M') AS visit_month,  -- '%M' describes the month in string
    count(visit_id) as number_visits
from
	fct_visits
group by visit_month 								-- group by month
order by number_visits desc 						-- arranges by high to low
-- This query aggregates visits by calendar month, 
-- combining all years into each respective month (e.g., all Januaries together).

| visit_month | number_visits |
|-------------|---------------|
| October     | 887           |
| December    | 880           |
| March       | 870           |


-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q2. Which diagnosis codes are most common?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters

select
	diagnosis_code,
    count(visit_id) as occurence
from
	gold.fct_visits
group by diagnosis_code
order by occurence desc
-- At this point, query returns all results but since the questions requests for most we limit the results to top 5
limit 7
-- From the result, we can see multiple codes with the same number of occurences.

| diagnosis_code | occurence |
|----------------|-----------|
| ICD_80.85      | 124       |
| ICD_37.80      | 123       |
| ICD_30.42      | 121       |
| ICD_16.57      | 121       |
| ICD_22.44      | 121       |
| ICD_04.03      | 120       |
| ICD_23.65      | 119       |


-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q3. What is the average visit duration per visit type?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters

select
	visit_type,
	avg(duration_min) as average_duration
from
	fct_visits
group by visit_type

| visit_type | average_duration |
|------------|------------------|
| Emergency  | 94.2041          |
| Inpatient  | 94.3209          |
| Outpatient | 95.6938          |

-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q4. Who are the top 5 doctors by patient count?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters
select * from gold.dim_doctors


select
	doctor_id,
    count(patient_id) as number_of_patients
from
	gold.fct_visits
group by doctor_id
-- This query gives us the number of patients per doctor.
-- In the table dim_doctors we can match the doctor_id to the names using the 'join'.

select
    dd.doctor_name,
    count(fv.patient_id) as number_of_patients
from
	fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id
group by dd.doctor_name
order by count(fv.patient_id) desc
limit 5

| doctor_name      | number_of_patients |
|------------------|--------------------|
| Ashley Davis     | 126                |
| Brandon Hahn     | 126                |
| Christopher Hill | 123                |
| Kelly Allen      | 117                |
| Joseph Jenkins   | 117                |


-- ++++++++++++++++++++++++++++++++++++++++++++++
-- Q5. What is the total revenue (cost) generated by each specialty?
-- ++++++++++++++++++++++++++++++++++++++++++++++
-- Let's view parameters in a unified table (dim_doctors and fct_visits) using 'outer join'.
 
select * 
from fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id 

-- 
select
	specialty,
    sum(cost_usd) as total_revenue
from fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id 
group by specialty
order by total_revenue desc				-- 'Order by' highlights revenue from high to low.

| specialty        | total_revenue |
|------------------|---------------|
| Dermatology      | 4923654.18    |
| Orthopedics      | 4353305.58    |
| Neurology        | 3698291.97    |
| Psychiatry       | 3323575.49    |
| Pediatrics       | 3292293.10    |
| General Medicine | 2953695.37    |
| Cardiology       | 2610840.87    |

-- ++++++++++++++++++++++++++++++++++++++++++++++
-- Q6. List patients with more than 3 visits in the last 6 months.
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters
select * from gold.dim_patients


select
	*
from
	gold.fct_visits
where datename(month visit_date) is 'february'



select 
	patient_id,
	count(visit_id),
    year(visit_date) years
from
	gold.fct_visits
group by patient_id

order by years

select 
	dp.patient_name,
    date_format(visit_date,'%M %Y'), -- contains nonaggregated
    count(fv.visit_id) as number_of_visit
from fct_visits as fv
join dim_patients as dp
on fv.patient_id = dp.patient_id
group by dp.patient_name
where date_format(visit_date) = 'january 2025' -- linked to non aggregated

select 
	dp.patient_name,
    count(fv.visit_id) as number_of_visit
from fct_visits as fv
join dim_patients as dp
on fv.patient_id = dp.patient_id
group by dp.patient_name
-- Returns patients and the number of visits.

with prep as (select 
	dp.patient_name,
    count(fv.visit_id) as number_of_visit
from fct_visits as fv
join dim_patients as dp
on fv.patient_id = dp.patient_id
group by dp.patient_name
)
select 
	prep,
	date_format(visit_date,'%M %Y') as period
from fct_visits
where date_format(visit_date, '%M %Y') > 'january 2025' 




select
	patient_id,
    count(visit_id),
    date_format(visit_date, '%M %Y') as dates
from fct_visits
group by patient_id
order by date_format(visit_date, '%M %Y') desc

select 
	patient_id,
    date_format(visit_date, '%M %Y') as dates
from
	fct_visits
where year(visit_date) > '2024'
and month(visit_date) > 'january'
    
where date_format(visit_date, '%M %Y') > 'february 2025'

-- ++++++++++++++++++++++++++++++++++++++++++++++
-- Q8. What is the average cost per visit by visit type?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters

select
	visit_type,
	avg(cost_usd) as average_cost
from
	fct_visits
group by visit_type

| visit_type | average_cost |
|------------|--------------|
| Emergency  | 2501.154347  |
| Inpatient  | 2549.095930  |
| Outpatient | 2497.520041  |


-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q9. Which doctor has the highest average visit duration?
-- ++++++++++++++++++++++++++++++++++++++++++++++
-- This requires data from visits and doctor table

select
	dd.doctor_name,
	avg(duration_min) as average_duration
from
	fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id
group by doctor_name
order by average_duration desc
limit 1

| doctor_name  | average_duration |
|--------------|------------------|
| Dale Edwards | 106.1028         |


-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q10. How many unique patients visited each doctor?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters

-- First we can find the number of patients for each doctor
select
    dd.doctor_name,
    count(fv.patient_id) as number_of_patients
from
	fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id
group by dd.doctor_name
order by count(fv.patient_id) desc


-- the question is asking for unique patients per doctor.
-- we are goign to count each distinct patient 
select
	dd.doctor_name,
	count(distinct fv.patient_id) as unique_patients
from
	fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id
group by doctor_name
order by unique_patients desc


| doctor_name          | unique_patients |
|----------------------|-----------------|
| Christopher Hill     | 116             |
| Ashley Davis         | 116             |
| Brandon Hahn         | 114             |
| Larry Williams       | 107             |
| Kelly Allen          | 105             |
| Stephen Owens        | 104             |
| Richard Ward         | 103             |


-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q11. What are the top 3 most frequent diagnosis codes per specialty?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters
select * from gold.dim_doctors


with ggg as (
select
	doctor_id,
    specialty
from
	dim_doctors
)
select 
	g.ggg,
	distinct diagnosis_code
from 
	fct_visits as fv
join ggg as g
on fv.doctor_id = g.doctor_id
group by g.specialty



with diagnosis as (select
	diagnosis_code,
	count(diagnosis_code)
from
	fct_visits
group by diagnosis_code
order by count(diagnosis_code) desc
)

select
	*,
	specilaty,
    








select
    dd.specialty,
    fv.diagnosis_code,
	count( distinct fv.diagnosis_code) as ggg 
from
	fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id
group by fv.diagnosis_code
order by dd.specialty desc
limit 3




select
    dd.specialty,
	count( distinct fv.diagnosis_code) as ggg 
from
	fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id
group by dd.specialty
order by dd.specialty desc
limit 3



-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q12. Identify the gender distribution of patients per visit type?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters
select * from dim_patients

select
	fv.visit_type,
    count(distinct fv.patient_id),
    count(distinct dp.patient_gender) as gender_distribution
from fct_visits as fv
join dim_patients as dp
group by fv.visit_type


select
	fv.visit_type,
    count(distinct fv.visit_id),
    count(distinct fv.patient_id),
    count(distinct dp.patient_gender) as gender_distribution
from fct_visits as fv
join dim_patients as dp
group by fv.visit_type


SELECT visit_type, gender, COUNT(*) AS count
 FROM visits v
 JOIN patients p ON v.patient_id = p.patient_id
 GROUP BY visit_type, gender;



-- ++++++++++++++++++++++++++++++++++++++++++++++
-- Q14. What is the total cost of inpatient vs outpatient visits over the past year?
-- ++++++++++++++++++++++++++++++++++++++++++++++


select
	visit_type,
	sum(cost_usd) as total_cost
from
	fct_visits
where visit_type != 'Emergency'
group by visit_type

| visit_type | total_cost |
|------------|------------|
| Inpatient  | 8317700.02 |
| Outpatient | 8466592.94 |


