/*
Here, business insights are generated from facts and dimension tables created in
the gold schema. All questions are answered based on information from dim_ and fct_.
 

*/
use gold
-- ++++++++++++++++++++++++++++++++++++++++++++++
-- Q1. How many total visits occurred each month?
-- ++++++++++++++++++++++++++++++++++++++++++++++
-- every visit is recorded as per visit_id. 
select * from gold.fct_visits

select
	visit_date,
    count(visit_id) as total_visits
from
	fct_visits
group by visit_date
order by visit_date
-- this query only delivers visits per day. we need to extract/view the month of visit_date

select
	DATE_FORMAT(visit_date, '%M %Y') AS visit_month_year,  
    count(visit_id) as number_visits
from
	fct_visits
group by visit_month_year 								-- group by month
order by number_visits 
-- Formatting the data according to month and year reflects vists by month of the years.
-- The questions seeks to find the visit by month only. we eliminate the year (%Y) of the month

select
	DATE_FORMAT(visit_date, '%M') AS visit_month,  -- '%M' describes the month in string
    count(visit_id) as number_visits
from
	fct_visits
group by visit_month 								-- group by month
order by number_visits desc 						-- arranges by high to low
-- This query aggregates visits by calendar month, 
-- combining all years into each respective month (e.g., all Januaries together).

| visit_month | number_visits |
|-------------|---------------|
| October     | 887           |
| December    | 880           |
| March       | 870           |


-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q2. Which diagnosis codes are most common?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters

select
	diagnosis_code,
    count(visit_id) as occurence
from
	gold.fct_visits
group by diagnosis_code
order by occurence desc
-- At this point, query returns all results but since the questions requests for most we limit the results to top 5
limit 7
-- From the result, we can see multiple codes with the same number of occurences.

| diagnosis_code | occurence |
|----------------|-----------|
| ICD_80.85      | 124       |
| ICD_37.80      | 123       |
| ICD_30.42      | 121       |
| ICD_16.57      | 121       |
| ICD_22.44      | 121       |
| ICD_04.03      | 120       |
| ICD_23.65      | 119       |


-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q3. What is the average visit duration per visit type?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters

select
	visit_type,
	avg(duration_min) as average_duration
from
	fct_visits
group by visit_type

| visit_type | average_duration |
|------------|------------------|
| Emergency  | 94.2041          |
| Inpatient  | 94.3209          |
| Outpatient | 95.6938          |

-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q4. Who are the top 5 doctors by patient count?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters
select * from gold.dim_doctors


select
	doctor_id,
    count(patient_id) as number_of_patients
from
	gold.fct_visits
group by doctor_id
-- This query gives us the number of patients per doctor.
-- In the table dim_doctors we can match the doctor_id to the names using the 'join'.

select
    dd.doctor_name,
    count(fv.patient_id) as number_of_patients
from
	fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id
group by dd.doctor_name
order by count(fv.patient_id) desc
limit 5

| doctor_name      | number_of_patients |
|------------------|--------------------|
| Ashley Davis     | 126                |
| Brandon Hahn     | 126                |
| Christopher Hill | 123                |
| Kelly Allen      | 117                |
| Joseph Jenkins   | 117                |


-- ++++++++++++++++++++++++++++++++++++++++++++++
-- Q5. What is the total revenue (cost) generated by each specialty?
-- ++++++++++++++++++++++++++++++++++++++++++++++
-- Let's view parameters in a unified table (dim_doctors and fct_visits) using 'outer join'.
 
select * 
from fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id 

-- 
select
	specialty,
    sum(cost_usd) as total_revenue
from fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id 
group by specialty
order by total_revenue desc				-- 'Order by' highlights revenue from high to low.

| specialty        | total_revenue |
|------------------|---------------|
| Dermatology      | 4923654.18    |
| Orthopedics      | 4353305.58    |
| Neurology        | 3698291.97    |
| Psychiatry       | 3323575.49    |
| Pediatrics       | 3292293.10    |
| General Medicine | 2953695.37    |
| Cardiology       | 2610840.87    |

-- ++++++++++++++++++++++++++++++++++++++++++++++
-- Q6. List patients with more than 3 visits in the last 6 months.
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters
select * from gold.dim_patients

select
	*
from
	gold.fct_visits
where datename(month visit_date) is 'february'



select 
	dp.patient_name,
    date_format(visit_date,'%M %Y'), -- contains nonaggregated
    count(fv.visit_id) as number_of_visit
from fct_visits as fv
join dim_patients as dp
on fv.patient_id = dp.patient_id
group by dp.patient_name
where date_format(visit_date) = 'january 2025' -- linked to non aggregated

select 
	dp.patient_name,
    count(fv.visit_id) as number_of_visit
from fct_visits as fv
join dim_patients as dp
on fv.patient_id = dp.patient_id
group by dp.patient_name
-- Returns patients and the number of visits.

with prep as (select 
	dp.patient_name,
    count(fv.visit_id) as number_of_visit
from fct_visits as fv
join dim_patients as dp
on fv.patient_id = dp.patient_id
group by dp.patient_name
)
select 
	prep,
	date_format(visit_date,'%M %Y') as period
from fct_visits
where date_format(visit_date, '%M %Y') > 'january 2025' 


select 
	patient_id,
    date_format(visit_date, '%M %Y') as dates
from
	fct_visits
where year(visit_date) > '2024'
and month(visit_date) > 'january'
    
where date_format(visit_date, '%M %Y') > 'february 2025'

-- running few scripts returns error.
-- Let's look outside the box with this challenge


SELECT 
    dp.patient_name, 
    COUNT(*) AS visit_count
FROM fct_visits AS fv
JOIN dim_patients AS dp 
ON fv.patient_id = dp.patient_id
WHERE fv.visit_date >= CURDATE() - INTERVAL 6 MONTH  						-- all we ghad to do was to use the date function here.
GROUP BY dp.patient_name
HAVING COUNT(*) > 3;

| patient_name        | visit_count |
|---------------------|-------------|
| Rebecca Valencia    | 5           |
| James Parks         | 7           |
| Whitney Peters      | 6           |
| Paul Castaneda      | 10          |
| Ruben Dunn          | 6           |
| Tracy Ballard       | 5           |
| Joshua Blair        | 8           |
| Daniel Murphy       | 4           |
| Julie Dominguez     | 10          |


-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q7. Show daily patient traffic for emergency visits in the last 30 days.
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters

SELECT 
	visit_date, 
	COUNT(*) AS emergency_visits
FROM fct_visits
WHERE visit_type = 'Emergency'
AND visit_date >= CURDATE() - INTERVAL 30 DAY 
GROUP BY visit_date
ORDER BY visit_date;

| visit_date | emergency_visits |
|------------|------------------|
| 2025-06-24 | 5                |
| 2025-06-25 | 5                |
| 2025-06-26 | 4                |
| 2025-06-27 | 3                |
| 2025-06-28 | 3                |
| 2025-06-29 | 4                |



-- ++++++++++++++++++++++++++++++++++++++++++++++
-- Q8. What is the average cost per visit by visit type?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters

select
	visit_type,
	avg(cost_usd) as average_cost
from
	fct_visits
group by visit_type

| visit_type | average_cost |
|------------|--------------|
| Emergency  | 2501.154347  |
| Inpatient  | 2549.095930  |
| Outpatient | 2497.520041  |


-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q9. Which doctor has the highest average visit duration?
-- ++++++++++++++++++++++++++++++++++++++++++++++
-- This requires data from visits and doctor table

select
	dd.doctor_name,
	avg(duration_min) as average_duration
from
	fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id
group by doctor_name
order by average_duration desc
limit 1

| doctor_name  | average_duration |
|--------------|------------------|
| Dale Edwards | 106.1028         |


-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q10. How many unique patients visited each doctor?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters

-- First we can find the number of patients for each doctor
select
    dd.doctor_name,
    count(fv.patient_id) as number_of_patients
from
	fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id
group by dd.doctor_name
order by count(fv.patient_id) desc


-- the question is asking for unique patients per doctor.
-- we are goign to count each distinct patient 
select
	dd.doctor_name,
	count(distinct fv.patient_id) as unique_patients
from
	fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id
group by doctor_name
order by unique_patients desc


| doctor_name          | unique_patients |
|----------------------|-----------------|
| Christopher Hill     | 116             |
| Ashley Davis         | 116             |
| Brandon Hahn         | 114             |
| Larry Williams       | 107             |
| Kelly Allen          | 105             |
| Stephen Owens        | 104             |
| Richard Ward         | 103             |


-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q11. What are the top 3 most frequent diagnosis codes per specialty?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters
select * from gold.dim_doctors


select
	fv.diagnosis_code,
    dd.specialty,
	count(*) as frequency
from
	fct_visits as fv
join dim_doctors as dd
on fv.doctor_id = dd.doctor_id
group by dd.specialty, fv.diagnosis_code
order by dd.specialty, frequency desc


| diagnosis_code | specialty        | frequency |
|----------------|------------------|-----------|
| ICD_02.56      | Cardiology       | 22        |
| ICD_07.00      | Cardiology       | 17        |
| ICD_37.80      | Cardiology       | 16        |
| ICD_14.65      | Cardiology       | 16        |
| ICD_02.02      | Cardiology       | 16        |
| ICD_04.03      | Cardiology       | 16        |


-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q12. Identify the gender distribution of patients per visit type?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters
select * from dim_patients

select
	fv.visit_type,
	dp.patient_gender,
    count(fv.patient_id) as patients_distribution  
from fct_visits as fv
join dim_patients as dp
on fv.patient_id = dp.patient_id
group by fv.visit_type, dp.patient_gender
order by fv.visit_type


| visit_type | patient_gender | patients_distribution |
|------------|----------------|-----------------------|
| Emergency  | Female         | 1135                  |
| Emergency  | Male           | 1277                  |
| Emergency  | Other          | 935                   |
| Inpatient  | Female         | 1087                  |
| Inpatient  | Male           | 1207                  |
| Inpatient  | Other          | 969                   |
| Outpatient | Female         | 1132                  |
| Outpatient | Male           | 1251                  |
| Outpatient | Other          | 1007                  |


-- ++++++++++++++++++++++++++++++++++++++++++++++
-- Q13. How many visits were made by patients over 60 years old?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters
select * from dim_patients

SELECT COUNT(*) AS total_visits
FROM fct_visits as  fv
JOIN dim_patients as dp 
ON fv.patient_id = dp.patient_id
WHERE TIMESTAMPDIFF(YEAR, dp.patient_birth_date, CURDATE()) > 60;

| total_visits |
|--------------|
| 3794         |

-- ++++++++++++++++++++++++++++++++++++++++++++++
-- Q14. What is the total cost of inpatient vs outpatient visits over the past year?
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters

SELECT 
    fv.visit_type, 
    SUM(cost_usd) AS total_cost
FROM fct_visits as fv
WHERE fv.visit_date >= ( SELECT MAX(visit_date) FROM fct_visits) - INTERVAL 1 YEAR		
-- using CURDATE() instead of selecting the last visit_date will use current system date, thus answers will differ every day
and visit_type != 'Emergency'															-- shows only inpatient vs outpatient
GROUP BY fv.visit_type;

| visit_type | total_cost |
|------------|------------|
| Inpatient  | 4310746.23 |
| Outpatient | 4332253.02 |


-- ++++++++++++++++++++++++++++++++++++++++++++++
--  Q15. Show visit trends by weekday (e.g., Monday, Tuesday, etc.).
-- ++++++++++++++++++++++++++++++++++++++++++++++
select * from gold.fct_visits		-- Run this query to view your parameters

SELECT 
    DAYNAME(visit_date) AS weekday, 
    COUNT(*) AS visit_count
FROM fct_visits
GROUP BY weekday
ORDER BY visit_count DESC;

| weekday   | visit_count |
|-----------|-------------|
| Sunday    | 1482        |
| Friday    | 1462        |
| Wednesday | 1445        |
| Monday    | 1429        |
| Tuesday   | 1410        |
| Saturday  | 1393        |
| Thursday  | 1379        |


